# Generated by Django 4.2.20 on 2025-04-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user_id',
            new_name='user',
        ),
    ]
